Convert Zesty <Url> to Mui <Link>
zesty-io/manager-ui pull request #1098
Opened 2022-05-20 18:20 UTC by rjpals

Closes #1064

2022-05-24 21:24 UTC, shrunyan commented
@rjpals is this ready for an incremental deploy?

2022-05-25 15:53 UTC, rjpals commented
@shrunyan Not yet. There are still a couple of styling issues, one of which is a MUI theme override that has not been implemented yet.

2022-06-01 04:36 UTC, agalin920 requested changes

2022-06-01 04:36 UTC, agalin920 commented on src/apps/code-editor/src/app/components/FileDrawer/components/LinkedContent/LinkedContent.js
> +                      margin: 0,
Does the mui Link component come with margin? Seems odd

2022-06-01 04:36 UTC, agalin920 commented on src/apps/code-editor/src/app/components/FileDrawer/components/LinkedContent/LinkedContent.js
> +                    <em sx={{ pr: 1 }}>{item.web.path}</em>
Since em is not a mui component I don't think em does anything here. Additionally seems weird you need padding on the right side of the text

2022-06-01 04:36 UTC, agalin920 commented on src/apps/content-editor/src/app/views/Dashboard/components/QuickJumps/QuickJumps.js
> +            sx={{ mt: 1.5, color: "primary.main" }}
You are overriding color with sx here but you are defining color="secondary". You can just define color="primary"

2022-06-01 04:36 UTC, agalin920 commented on src/apps/content-editor/src/app/views/ItemList/SetRow/PublishStatusCell/PublishStatusCell.js
> +          <ClockIcon fontSize="small" sx={{ color: "warning.main" }} />
Mui icons can take in a color prop <ClockIcon color='warning' />

2022-06-01 04:36 UTC, agalin920 commented on src/apps/content-editor/src/app/views/ItemList/SetRow/PublishStatusCell/PublishStatusCell.js
> +          <VisibilityIcon fontSize="small" sx={{ color: "success.main" }} />
Mui icon color prop

2022-06-01 04:36 UTC, agalin920 commented on src/apps/content-editor/src/app/views/ItemList/SetRow/PublishStatusCell/PublishStatusCell.js
> +          <VisibilityIcon fontSize="small" sx={{ color: "primary.main" }} />
Mui icon color prop

2022-06-02 16:26 UTC, agalin920 approved these changes
LGTM

2022-06-02 20:23 UTC, merged