MUI Dividers conversion
zesty-io/manager-ui pull request #1099
Opened 2022-05-23 15:30 UTC by d88naimi

2022-05-23 15:54 UTC, agalin920 commented on src/apps/content-editor/src/app/views/ItemEdit/Meta/ItemSettings/ContentInsights/ContentInsights.js
> +            mt: 1,
Can you simplify this to my: 1 please

2022-05-23 15:54 UTC, agalin920 commented on src/apps/content-editor/src/app/views/ItemEdit/Meta/ItemSettings/ContentInsights/ContentInsights.js
> +            mt: 1,
Can you simplify this to my: 1 please

2022-05-23 15:55 UTC, agalin920 commented on src/apps/content-editor/src/app/views/ItemEdit/Meta/ItemSettings/ContentInsights/ContentInsights.js
> +            mt: 1,
Can you simplify this to my: 1 please

2022-05-23 15:55 UTC, agalin920 commented on src/apps/settings/src/app/views/Instance/Instance.js
> +          mr: 2,
Can you simplify this to my: 1 mx: 2 please

2022-05-23 15:55 UTC, agalin920 commented on src/apps/settings/src/app/views/Instance/Instance.js
> +                  mt: 1,
Can you simplify this to my: 1 mx: 2 please

2022-05-23 15:55 UTC, agalin920 requested changes
See comments for changes

2022-05-24 15:53 UTC, agalin920 approved these changes
Approved

2022-05-24 16:25 UTC, shrunyan requested changes

2022-05-24 16:25 UTC, shrunyan commented on src/apps/content-editor/src/app/views/ItemEdit/Meta/ItemSettings/ContentInsights/ContentInsights.js
> +        <h4>Words Occurrences from the URL, Meta Title and Description</h4>
also lower case "occurrences"

2022-05-24 21:16 UTC, shrunyan approved these changes

2022-05-24 21:18 UTC, shrunyan commented
@d88naimi there is a test failing for `releases/members.spec.js`. Would you investigate what's happening there

2022-05-25 15:14 UTC, d88naimi commented on cypress/integration/content/headTags_spec.js
> +    cy.get("[data-cy=head]").click({ force: true });
contentNav wont close  event with `cy.get("[data-cy=contentNavButton]").click();` and is blocking the click of Head Tag button that's why I adde force true

2022-05-25 17:25 UTC, d88naimi commented
Made a new PR here https://github.com/zesty-io/manager-ui/pull/1111

2022-05-25 17:25 UTC, closed without merging