Convert FieldTypeUrl
zesty-io/manager-ui pull request #1213
Opened 2022-06-28 19:06 UTC by rjpals

~~This PR is dependent on the merge & publish of https://github.com/zesty-io/material/pull/28~~

Necessary theme changes have been merged

2022-07-01 04:33 UTC, agalin920 requested changes

2022-07-01 04:33 UTC, agalin920 commented on src/apps/content-editor/src/app/views/LinkCreate/LinkCreate.js
> +import { FieldTypeUrl } from "@zesty-io/material";
Watch out for duplicate imports

This should be 

import { FieldTypeText, FieldTypeUrl } from "@zesty-io/material";

2022-07-01 04:33 UTC, agalin920 commented on src/apps/content-editor/src/app/views/LinkEdit/LinkEdit.js
> +import { FieldTypeUrl } from "@zesty-io/material";
Same comment regarding duplicate import

2022-07-06 22:22 UTC, shrunyan approved these changes

2022-07-06 22:22 UTC, merged