Typescript
zesty-io/manager-ui pull request #1241
Opened 2022-07-22 22:58 UTC by rjpals

This adds the ability to use TypeScript and converts a single file (`src/shell/notifications.js`) to TS. 

With this configuration, TS is entirely optional. The source tree consist of TS and JS interoperating with each other and developers will be able to freely choose between them (for now.) This will allow us to incrementally adopt TS without an all-out rewrite.

For information, see [the spec](https://docs.google.com/document/d/1e_ALIynxoEWcxB4pb6zl_tqzUKIpnxjS4oag2BAhScI)

2022-07-25 18:02 UTC, agalin920 requested changes

2022-07-25 18:02 UTC, agalin920 commented on src/shell/store/notifications.ts
> +type Action = {
Are we gonna go with 'type' over 'interface' ?

2022-07-25 18:02 UTC, agalin920 commented on src/shell/store/notifications.ts
> +type Data = {
I think Data is too arbitrary and not indicative enough of what this is. Shouldn't we should name this Notification? Especially in the case we ever need to export this type to a component

2022-07-25 18:04 UTC, agalin920 commented on package.json
> +    "@babel/preset-typescript": "^7.18.6",
Is this needed?

2022-07-25 18:06 UTC, agalin920 commented on src/shell/store/notifications.ts
> +export function notifications(state = [], action: Action) {
State should be defined

2022-07-25 21:04 UTC, shrunyan commented on src/shell/webpack.config.js
> +      /*
why has this been commented out?

2022-07-29 18:21 UTC, shrunyan approved these changes

2022-07-29 18:21 UTC, merged