Add support for CSV import redirect target type
zesty-io/manager-ui pull request #1317
Opened 2022-08-29 05:50 UTC by agalin920

- Added CSV parse functionality to look for column names and determine index as opposed to requiring user to have columns in a specific order
- Added ability to choose target type for a redirect
- Added more verbose error on notifications to better convey what might be incorrect/missing

<img width="772" alt="Screen Shot 2022-08-28 at 10 39 00 PM" src="https://user-images.githubusercontent.com/10054410/187131491-e8749ae0-59bc-4a4d-8fa3-427c7dc856fd.png">

2022-09-02 17:40 UTC, rjpals requested changes

2022-09-07 16:23 UTC, bltarkany approved these changes

2022-09-07 16:27 UTC, rjpals approved these changes

2022-09-07 22:23 UTC, shrunyan commented
May solve https://github.com/zesty-io/manager-ui/issues/1255

2022-09-07 22:39 UTC, merged