Feature: Content app sidebar redesign
zesty-io/manager-ui pull request #2197
Opened 2023-07-31 05:31 UTC by theofficialnar

- Updated content app sidebar
- Closes #1385 

### Preview
[content-app-sidebar.webm](https://github.com/zesty-io/manager-ui/assets/28705606/d2597b42-ba4b-4556-b745-4cab6d51f1fa)

2023-07-31 11:08 UTC, zcolah requested changes
@agalin920 
1. The sidebar resizing currently has a lot of lag and is not a smooth experience. It responds late sometimes, bounces back to a wider size when being made small, and sometimes skips frames. This does not happen on each attempt. It happens on one out of every 3 attempts on average. Please refer to Slack's and Clickup's sidebar for examples of smooth resizing.

2023-07-31 11:37 UTC, zcolah commented
@shrunyan could we add the tooltip helper text on hover functionality to the scope of this project or should it be a different project? You can see the tooltip helper text bubbles here: https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/App-Navigation?type=design&node-id=545%3A202423&mode=design&t=24AXSMD60gHgmc5T-1

2023-07-31 11:52 UTC, zcolah requested changes
@theofficialnar 
1. The flow of when a user hovers over a dataset or multi page model list item and clicks on the plus button to create an item does not follow the logic defined here in Figma: https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/App-Navigation?type=design&node-id=52%3A71151&mode=design&t=24AXSMD60gHgmc5T-1

Instead of directly leading to the create item page, it instead opens a modal that is not part of the flow (see screenshot below): 
<img width="1440" alt="CleanShot 2023-07-31 at 16 43 40@2x" src="https://github.com/zesty-io/manager-ui/assets/22625919/d02c2fa0-53a2-4cc7-ae77-38ac251f1a4d">


2. When a user searches for an item successfully or unsuccessfully we want to hide the dashboard and releases tabs. Unfortunately at the moment this is not the case for when a user searches successfully. 

Figma Reference to see defined design spec for search results: https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/App-Navigation?type=design&node-id=52%3A70317&mode=design&t=24AXSMD60gHgmc5T-1


See screenshot to see issue: 

![CleanShot 2023-07-31 at 17 17 09@2x](https://github.com/zesty-io/manager-ui/assets/22625919/bac86ef3-513a-4561-bfd1-b37a6fe0078a)

3. The small buttons that appear in the list items are missing hover states. 

![CleanShot 2023-07-31 at 17 18 52@2x](https://github.com/zesty-io/manager-ui/assets/22625919/34038ba4-f93d-451d-af05-a02cbc103383)

Please see the hover states here: 
https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/App-Navigation?type=design&node-id=4%3A16337&mode=design&t=24AXSMD60gHgmc5T-1
 
4. See VQA Issues Here: 
https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/App-Navigation?type=design&node-id=655%3A63725&mode=design&t=24AXSMD60gHgmc5T-1

2023-07-31 22:15 UTC, theofficialnar commented on src/shell/components/NavTree/components/NavTreeItem.tsx
> +        "& .MuiTreeItem-content": {
Adding these set of changes on the theme level will also affect the look of those components using the tree item already which I am not sure is a desired outcome that's why I just added these style changes locally.

2023-07-31 22:25 UTC, theofficialnar commented on src/apps/content-editor/src/app/components/ContentNav/index.tsx
> +          open
It's a required prop on the component though that's why I added it initially. But I'll just change the component to make it optional with a default value of true.

2023-07-31 22:29 UTC, theofficialnar commented on src/apps/content-editor/src/app/components/ContentNav/index.tsx
> +              borderRadius: 0.5,
Currently waiting on Zosh's feedback regarding this.

2023-08-01 00:03 UTC, theofficialnar commented on src/apps/content-editor/src/app/ContentEditor.js
> +              <ResizableContainer
Added on latest commit

2023-08-01 00:03 UTC, theofficialnar commented on src/apps/content-editor/src/app/components/ContentNav/components/NavError.tsx
Updated, moved to root of folder

2023-08-01 00:04 UTC, theofficialnar commented on src/shell/components/AppSidebar/index.tsx
> +              backgroundColor: isLightMode ? "common.white" : "grey.900",
Updated, added background.paper on dark theme pallete

2023-08-01 00:04 UTC, theofficialnar commented on src/shell/components/AppSidebar/index.tsx
> +    const themeMode = useMemo(() => {
Removed usememo

2023-08-01 02:05 UTC, theofficialnar commented on src/apps/content-editor/src/app/components/ContentNav/index.tsx
> +                        borderRadius: 0.5,
Waiting for Zosh's feedback on the icon buttons

2023-08-01 02:22 UTC, theofficialnar commented on src/apps/content-editor/src/app/components/ContentNav/index.tsx
> +                backgroundColor: "primary.dark",
Changed this to a regular button and color update will be done on theme

2023-08-01 02:22 UTC, theofficialnar commented on src/apps/content-editor/src/app/components/ContentNav/index.tsx
> +                    backgroundColor: "primary.dark",
Changed this to a regular button and color update will be done on theme

2023-08-01 19:31 UTC, zcolah requested changes
1. By default please keep all pages/items expanded by default instead of closed.

2023-08-01 20:12 UTC, zcolah requested changes
1. Randy has requested that we hide Releases for now as a tab in Content.

2023-08-01 20:21 UTC, zcolah requested changes
1. Please make the help tooltips show up after a delay of 1 second instead of 2 seconds

2023-08-02 10:03 UTC, theofficialnar commented on src/apps/content-editor/src/app/components/ContentNav/index.tsx
> +              borderRadius: 0.5,
Created a new icon button inside the @zesty-io/material-ui repo that is able to render a contained variant

2023-08-02 10:03 UTC, theofficialnar commented on src/apps/content-editor/src/app/components/ContentNav/index.tsx
> +                        borderRadius: 0.5,
Created a new icon button inside the @zesty-io/material-ui repo that is able to render a contained variant

2023-08-06 22:51 UTC, theofficialnar commented
@agalin920 I'll try to look for a way to optimize how the tree data is built. As for the NavTree being rendered 3 times, I don't think there's really any way around it since I had to put in 3 different NavTree components, each for Pages, Headless and Hidden items. 

I do agree that flattening out the filter list would make it faster since we'll only have to render 1 NavTree in that case but I think I still have to make some loops to add in the icons and the hover action elements for each nav item that matches the filter keyword.

2023-08-10 20:02 UTC, merged