Feat: Various app sidebar redesign
zesty-io/manager-ui pull request #2225
Opened 2023-08-15 06:25 UTC by theofficialnar

Updated app sidebars for the following:

- Schema
- Media
- Reports
- Apps

### Schema
![Screenshot_20230815_142144](https://github.com/zesty-io/manager-ui/assets/28705606/43b6ea0f-8900-4c89-8086-31739cd4c54a)

### Media
![Screenshot_20230815_142155](https://github.com/zesty-io/manager-ui/assets/28705606/345a8419-7039-4900-93f4-0286450d23ea)

### Reports
![Screenshot_20230815_142129](https://github.com/zesty-io/manager-ui/assets/28705606/9a0c1a5d-0f7f-4c41-a7bb-8d9efa4e9658)

### Apps
![Screenshot_20230815_142100](https://github.com/zesty-io/manager-ui/assets/28705606/20d368a2-ca6f-4f36-96d6-dbdb9321e75c)

2023-08-15 08:12 UTC, theofficialnar commented on src/apps/marketplace/src/app/components/InstallApp.tsx
> +        <Box
Updated

2023-08-15 08:12 UTC, theofficialnar commented on src/apps/marketplace/src/app/components/Sidebar.tsx
> +    if (!!installedApps.length) {
Removed

2023-08-15 08:14 UTC, theofficialnar commented on src/apps/media/src/app/components/FolderMenu.tsx
> +  const hiddenGroups =
I've actually tried this but it doesn't work. `useLocalStorage` doesn't get the updated data somehow

2023-08-15 08:14 UTC, theofficialnar commented on src/apps/media/src/app/components/Sidebar/Folders.tsx
> +    if (!!binGroups?.length) {
Removed

2023-08-15 08:15 UTC, theofficialnar commented on src/apps/media/src/app/components/Sidebar/NewSidebar.tsx
> +import { FC, useEffect, useState, useRef } from "react";
Renamed to index.tsx

2023-08-15 08:15 UTC, theofficialnar commented on src/apps/schema/src/app/components/Sidebar/ModelList.tsx
> +    if (!!models.length) {
Removed

2023-08-15 08:15 UTC, theofficialnar commented on src/shell/components/AppSidebar/index.tsx
> +                          sx={{ fontSize: 18 }}
I've changed all instances of fontSize: 18 to small

2023-08-15 16:44 UTC, zcolah requested changes
@Nar overall great job like always. 3 bugs/requests. 

1. User should be able to drag and drop files into ecobins in the sidebar. @agalin920 made this so he should be able to give guidance on this to you so you can make this quickly.

2. File uploaded should appear at the start of the list/grid and not at the end of the grid/list

3.   In the Add Folder Modal, please add all instance bins as options in the Select Folder dropdown. 

https://www.loom.com/share/eaad82a60e744d2c9769fa20796b4f0d?from_recorder=1&focus_title=1

2023-08-15 16:48 UTC, zcolah requested changes
Please make the Instance Bin get selected when the user clicks on add subfolder to an Instance Bin in the title bar or in the sidebar. 

See Loom: https://www.loom.com/share/204097fac8a645fc88ec8a37bf74c702

2023-08-16 06:10 UTC, theofficialnar commented
@zcolah added the following as requested:

- Show all folders and ecobins when clicking the generic + folder button
- Automatically select ecobin when adding a new folder in ecobin root
- Show warning message when attempting to drag a folder to a diff ecobin
- Allow dragging of file to parent ecobin's root

> File uploaded should appear at the start of the list/grid and not at the end of the grid/list
As discussed this has already been resolved elsewhere

2023-08-17 07:17 UTC, theofficialnar commented on src/apps/media/src/app/components/Sidebar/index.tsx
> +  const renderTitleButton = () => {
Gotcha, moved it to its own component

2023-08-18 15:22 UTC, zcolah requested changes
Was making a demo video and discovered two bugs which we need to resolve ideally before shipping. 

1. In the create folder experience, remove none as an option from the dropdown, and make the default selection as the first ecobin in an instance
2. Always show the instance ecobin even if it has 0 sub folders 

See video for more details: https://www.loom.com/share/65acb0242c4345f495c2e7656f0ecaf9

2023-08-23 17:28 UTC, shrunyan commented
![image](https://github.com/zesty-io/manager-ui/assets/208819/5f296912-fbb3-481e-8660-d089690d2976)

app crash when clearing local storage

2023-08-23 23:10 UTC, zcolah requested changes
**Problem**
Currently it is not evident to a user what order they have sorted everything by.

<img width="440" alt="CleanShot 2023-08-24 at 04 38 57@2x" src="https://github.com/zesty-io/manager-ui/assets/22625919/58ee6356-a43c-4445-bbd0-f84828ff7af5">

**Solution**
Please have the selected menu option be in the selected state so that it is clear to the user what the current sorting is.

2023-08-24 00:28 UTC, merged