Feature: Schema title bar
zesty-io/manager-ui pull request #2246
Opened 2023-09-05 06:06 UTC by theofficialnar

2023-09-06 05:06 UTC, theofficialnar commented on src/apps/schema/src/app/components/AddFieldModal/views/FieldForm.tsx
> +          borderBottom: `2px solid ${theme.palette.border}`,
Updated, changed to `borderColor: "border"` instead

2023-09-06 10:32 UTC, zcolah requested changes
1. [Visual QA Feedback on Figma](https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/Zesty-3.0-Revamp?type=design&node-id=1937%3A217375&mode=design&t=myTMEkSKQfqXaqm5-1)

2. [Make Info Tab Updates in Figma](https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/Zesty-3.0-Revamp?type=design&node-id=1958%3A264624&mode=design&t=QXBqnuJ6L18Q7Y3L-1): There is a poor contrast on the Info Tab page due to the change in the background color to Grey.50. I had not anticipated this and hence need to request 4 changes to be made to the content items in the Info Tab. Apologies for the same. 

3. Update Icon of All Models in the Sidebar and in the Breadcrumbs to be database-search (sent the icon SVG on Slack). Please also ensure this PR is connected to this [issue](https://github.com/zesty-io/manager-ui/issues/2247).  See screenshot below

![image](https://github.com/zesty-io/manager-ui/assets/22625919/81f4315c-ed28-4b32-8023-51bc3e6d53cc)

2023-09-06 10:44 UTC, zcolah requested changes
**Info Tab Update**
There is a poor contrast on the Info Tab page due to the change in the background color to Grey.50. I had not anticipated this and hence need to request 4 changes to be made to the content items in the Info Tab. 

See Figma design here: https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/Zesty-3.0-Revamp?type=design&node-id=1958%3A264624&mode=design&t=QXBqnuJ6L18Q7Y3L-1

Apologies for the same.

2023-09-06 12:12 UTC, zcolah requested changes
Please update the icon of All Models in the Sidebar and in the Breadcrumb to be database-search. I have sent the icon SVG via Slack. 

![image](https://github.com/zesty-io/manager-ui/assets/22625919/81f4315c-ed28-4b32-8023-51bc3e6d53cc)

2023-09-06 14:14 UTC, zcolah requested changes
NA

2023-09-06 14:42 UTC, zcolah requested changes
Overall Great Job @theofficialnar, please make the following changes to the designs.

1. [Visual QA Feedback on Figma](https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/Zesty-3.0-Revamp?type=design&node-id=1937%3A217375&mode=design&t=myTMEkSKQfqXaqm5-1)

2. [Make Info Tab Updates in Figma](https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/Zesty-3.0-Revamp?type=design&node-id=1958%3A264624&mode=design&t=QXBqnuJ6L18Q7Y3L-1): There is a poor contrast on the Info Tab page due to the change in the background color to Grey.50. I had not anticipated this and hence need to request 4 changes to be made to the content items in the Info Tab. Apologies for the same. 

3. [Update Icon of All Models in the Sidebar and in the Breadcrumbs](https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/Zesty-3.0-Revamp?type=design&node-id=917%3A237213&mode=design&t=QXBqnuJ6L18Q7Y3L-1) to be database-search (sent the icon SVG on Slack). Please also ensure this PR is connected to this [issue](https://github.com/zesty-io/manager-ui/issues/2247).  See screenshot below

![image](https://github.com/zesty-io/manager-ui/assets/22625919/81f4315c-ed28-4b32-8023-51bc3e6d53cc)

4. Update API Tab Padding Issues. Currently the API Tab spacing looks to be off. So we need to make two changes specifically as listed below. You can also refer to this [Figma file](https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/Zesty-3.0-Revamp?type=design&node-id=1960%3A265835&mode=design&t=QXBqnuJ6L18Q7Y3L-1) to see the spacing rules.

  a. Make the top padding on this div from 16px to 0px. 
  <img width="1440" alt="CleanShot 2023-09-06 at 19 43 56@2x" src="https://github.com/zesty-io/manager-ui/assets/22625919/b6d24b7e-14b2-4570-b0d0-8decdc133018">

  b. Make the bottom padding on this div from 20px to 16px
  <img width="1440" alt="CleanShot 2023-09-06 at 19 45 30@2x" src="https://github.com/zesty-io/manager-ui/assets/22625919/3b7a23e4-cfb7-46a9-90b8-22c12a4dd702">

2023-09-07 22:50 UTC, zcolah requested changes
1. Update the info icon size for the description field in the right sidebar to be 12px by 12px. Note: This is a bug not originally in scope. 

2. Make the color of the title in each field list item to be typography.primary. 

<img width="887" alt="CleanShot 2023-09-08 at 04 18 22@2x" src="https://github.com/zesty-io/manager-ui/assets/22625919/1945ec61-3cff-4b86-b64a-24cfd255427b">

3. Please rename Copy ZUID to Copy Model ZUID

<img width="337" alt="CleanShot 2023-09-08 at 04 19 36@2x" src="https://github.com/zesty-io/manager-ui/assets/22625919/d22b5c0a-a279-4fa9-92f8-b0fa4ff69c5a">

4. Please rename copy zuid here to "Copy Field ZUID"
<img width="477" alt="CleanShot 2023-09-08 at 04 20 00@2x" src="https://github.com/zesty-io/manager-ui/assets/22625919/71d424c5-d032-4897-b7dc-ed7f7f6c559f">

2023-09-08 19:32 UTC, merged