Feature: Settings sidebar revamp
zesty-io/manager-ui pull request #2266
Opened 2023-09-17 22:52 UTC by theofficialnar

Closes #2169 

### Preview
![settings](https://github.com/zesty-io/manager-ui/assets/28705606/21650496-5db8-4d76-8d10-a6ce9bb129c8)

2023-09-17 23:09 UTC, theofficialnar commented on src/shell/services/types.ts
> +export interface StyleCategory {
Updated

2023-09-17 23:09 UTC, theofficialnar commented on src/apps/settings/src/app/components/Nav/SettingsNav.tsx
> +const HeaderComponent: FC<HeaderComponentProps> = ({ title }) => {
Updated

2023-09-17 23:09 UTC, theofficialnar commented on src/apps/settings/src/app/components/Nav/SettingsNav.tsx
> +interface HeaderComponentProps {
Updated

2023-09-18 08:26 UTC, zcolah requested changes
Great job as always @theofficialnar. Two key things to fix. 

1. Empty State defined is not present 
<img width="508" alt="CleanShot 2023-09-18 at 13 54 24@2x" src="https://github.com/zesty-io/manager-ui/assets/22625919/6071d3e6-47ad-4341-8e32-a720cc9ec03c">

2. Please make the default width of all sidebars to be the minimum width rather than being a width between the min and max.

2023-10-02 19:38 UTC, merged