Date field revamp
zesty-io/manager-ui pull request #2562
Opened 2024-02-21 08:22 UTC by jomarmontuya

closes https://github.com/zesty-io/manager-ui/issues/2414

- [x] Check with andres if timestamp is needed
- [x] Better approach on getting the zesty-orange background
- [x] Deployment to stage for early VQA and bugs ask @theofficialnar

2024-02-21 08:26 UTC, jomarmontuya commented
![Uploading image.png…]()

2024-02-21 08:27 UTC, jomarmontuya commented
![image](https://github.com/zesty-io/manager-ui/assets/61284357/6f9fd588-5e35-4144-a856-905d45cad473)

2024-02-22 07:43 UTC, jomarmontuya commented
https://github.com/zesty-io/manager-ui/assets/61284357/b2cf9e7d-b445-4979-9ad8-647227a86e5e

@zcolah This is the initial draft preview of this component. I think it would be better if we can ask @theofficialnar  to deploy it for you to see it yourself.

2024-02-28 07:18 UTC, zcolah commented
A few functionalities are not present: 
1. The Date Selection Pop Up should appear and update when typing
2. If the field is clear with no date prior to this, then open the date picker with the current date (aka today’s date) selected

2024-02-29 10:49 UTC, jomarmontuya commented
@agalin920  @theofficialnar 

Hello both,  Seeking your help, on how we can possibly achieve this experience, in our calendar, I have been researching on how to make it possible using core mui-x and can't seem to find a way to copy the same experience.

I would assume we have to write custom logic and override mui-x datepicker functionality to make it work, but I wanted to hear your thoughts, maybe you've encounter the same issues in the past. 

I was able to make it work but only partials not as fluid as the video below, and the core mui-x only supports custom inputs  but only specifics to defined format.

https://github.com/zesty-io/manager-ui/assets/61284357/e01fd291-c891-4d5f-a618-6a8cb23b7cdb

2024-03-01 07:20 UTC, jomarmontuya commented
@agalin920  Thanks Andres, I will complete first the other requirements and get back to you on this one.

2024-03-04 15:52 UTC, jomarmontuya commented
@agalin920 

```
 1. The Date Selection Pop Up should appear and update when typing
```
I was able to make the popup appear and set back the focus back to textfield when the TextField  is click, however this component needs to have state if we need realtime updates to the calendar picker. Because currently the picker date only updates after I complete typing the date in MMM DD, YYYY format.

```
2. If the field is clear with no date prior to this, then open the date picker with the current date (aka today’s date) selected
```

@zcolah  can you confirm this, as this is already implemented during our previous review. or I'm missing something?  

https://github.com/zesty-io/manager-ui/assets/61284357/04723027-d90b-4805-a52c-e99a2cb57af9


```
3. The experience of typing in a date is not fluid as per the expectations set. Please see requests and Google Calendar as a behavior reference.
```
This relates to the issue number one, also it looks like based on the requirements, we need to be able to accept different format inputs in the textfield. This is not possible at the moment with mui-x datePicker as we have to pick one format that we can use. 

![image](https://github.com/zesty-io/manager-ui/assets/61284357/8cc9f256-a4ae-4092-ad43-9dc7f1188371)

```
 4. Check the padding of the icon button
```
This will get solved on the inputAdornment theme change is merged.

2024-03-05 19:32 UTC, zcolah commented
@jomarmontuya I just met with @agalin920 and here are our two key takeaways: 

1. If the complexity to implement date formats 6, 7, 8 is too high and will take a full week, please do not do it. We will do it for a future iteration. 

2. The Loom video below should provide more context on what this means: If the field is clear with no date prior to this, then open the date picker with the current date (aka today’s date) selected
 
https://www.loom.com/share/4c2c18a4e60b4ec3ba81292381e38f69?from_recorder=1&focus_title=1

2024-03-06 06:16 UTC, jomarmontuya commented
@zcolah 

https://www.loom.com/share/3825bf5e763a49e881687702ddca7012

here's the updated one please let me know what you think about this.

2024-03-06 13:10 UTC, zcolah commented
Hi @jomarmontuya 
Thank you for this update. Currently it does fill the date in as expected but notice how it has the year part highlighted/selected. Could we instead have the month part be highlighted? 

![CleanShot 2024-03-06 at 18 39 29](https://github.com/zesty-io/manager-ui/assets/22625919/f8757920-0dde-426a-8cf2-9b0c61e98968)

2024-03-07 13:33 UTC, jomarmontuya commented
@zcolah  Thank you! here's the updated one 

https://www.loom.com/share/89c91db9a2b048cda5f22dcc105760b1

2024-03-07 13:47 UTC, jomarmontuya commented
@zcolah 

if there's existing value in the dateField saved in the database, then the user click the clear the datefield will be null, but when they open the picker again what should be the default selected date?

- [ ] Current saved date from database?
- [ ] Current day similar to as if empty?

cc: @agalin920

2024-03-10 15:06 UTC, jomarmontuya commented on src/apps/content-editor/src/app/components/Editor/Field/Field.tsx
> +            onChange={(date) => onDateChange(date, name, datatype)}
@agalin920  It is emitting localize date

2024-03-10 15:06 UTC, jomarmontuya commented on src/shell/components/FieldTypeDate/index.tsx
> +                      background: "#FF5D0A",
I'm working on update on the theme level as this date picker will be used as a component and can appear on different places

2024-03-10 15:06 UTC, jomarmontuya commented on src/shell/components/FieldTypeDate/index.tsx
> +        setTimeout(() => {
by default when browser see a diagog box, the focus will be set to the closes focusable element inside the dialog.

I've added a setTimeout to delay the focus on textfield, to ensure that the dialog is fully open and focus was set, before moving the focus to the textfield.

See more details here -> https://web.dev/learn/html/dialog#:~:text=By%20default%2C%20when%20a%20dialog,when%20the%20dialog%20is%20opened.

2024-03-11 15:01 UTC, zcolah commented on src/shell/components/FieldTypeDate/index.tsx
> +                    color: "white",
This should be primary.main

2024-03-11 15:02 UTC, zcolah commented on src/shell/components/FieldTypeDate/index.tsx
> +                    color: "white",
You can check this: https://zesty-io.github.io/material/?path=/story/theme--default

![CleanShot 2024-03-11 at 20 32 22](https://github.com/zesty-io/manager-ui/assets/22625919/eeb0e3a1-bbe6-4933-95d7-f6e354238f65)

2024-03-12 09:02 UTC, jomarmontuya commented
@shrunyan  - >https://github.com/zesty-io/material/pull/93

Please see related PR to move this for VQA

2024-03-14 00:28 UTC, jomarmontuya commented
@zcolah  This is up on dev you may proceed with VQA

2024-03-14 09:38 UTC, zcolah requested changes
@jomarmontuya

See Loom video that describes all of the issues below in more detail: https://www.loom.com/share/83204fcc82724beda555a7e49429f2e5

 1. Reduce the lag in showing the current date when the user opens the modal for the first time
 2. If possible please add a cursor indicator so that the user knows they are typing and knows where they are typing
 3. Add ability to update the entire date when it is highlighted/selected
 4. Once a user has selected a date via the Calendar pop up, the date input can go back to it's default non selected state. It does not need to be in active state and the year does not need to be highlighted.
 5. If there is an invalid date, then please immediately display an error message to a user. [See Figma design.](https://www.figma.com/file/zOI7oSH3fG1XDmmPzsP6PX/Zesty-3.0-Revamp?type=design&node-id=4080%3A27763&mode=dev&t=sOKSk2D0KnWplKAw-1)

2024-03-15 06:39 UTC, jomarmontuya commented
@zcolah with this feedback I've got I think I had to do a completely different approach here instead for the textfield.

Instead of using the mui datepicker field out of the box I might have to use a custom textfield to allow user a full typing experience, because as of now I don't think there's a way to add cursor to the textfield, as it would only allow you to edit the date base on the format we assign which is "MMM DD, YYYY" that's why you can only change it as a whole not individual characters

@agalin920 I was thinking the solution we talked about last time, using a custom textfield with regex to make it work.

2024-03-21 15:53 UTC, jomarmontuya commented
https://www.loom.com/share/138bafd09fc84528831118b562a96e73?sid=3433482c-0755-4ceb-9ba7-c61bde0ca290

@zcolah  here's the update regarding the datefield revamp 

cc @agalin920

2024-03-21 15:57 UTC, zcolah commented
Looks good, will test

2024-04-04 19:19 UTC, merged