[Content] Support dedicated TC Image field in SEO tab
zesty-io/manager-ui pull request #3044
Opened 2024-10-28 00:34 UTC by finnar-bin

Resolves #3021 

### Preview
![image](https://github.com/user-attachments/assets/f71e7fe7-eafb-4477-a30b-90d406c4969f)

2024-10-28 17:04 UTC, agalin920 requested changes

2024-10-28 17:04 UTC, agalin920 commented on src/apps/content-editor/src/app/views/ItemEdit/Meta/SocialMediaPreview/TwitterPreview.tsx
> +        getFile(String(item.data.tc_image), true)
Cant we use the resolver here?

2024-10-28 22:21 UTC, finnar-bin commented on src/apps/content-editor/src/app/views/ItemEdit/Meta/SocialMediaPreview/TwitterPreview.tsx
> +        getFile(String(item.data.tc_image), true)
Oh yeah, I needed to check if the zuid actually contains an image first, if not use the existing meta image. This reminds me to actually add that check which I forgot, I'll be making another commit to add it.

2024-10-28 22:50 UTC, finnar-bin commented on src/apps/content-editor/src/app/views/ItemEdit/Meta/SocialMediaPreview/TwitterPreview.tsx
> +        getFile(String(item.data.tc_image), true)
Updated to add the check I mentioned above

2024-10-28 22:52 UTC, agalin920 requested changes

2024-10-28 22:52 UTC, agalin920 commented on src/apps/content-editor/src/app/views/ItemEdit/Meta/SocialMediaPreview/TwitterPreview.tsx
> +        getFile(String(item.data.tc_image), true)
Hmm why not just use html image onError callback? that would suffice to tell if its not an image right?

2024-10-28 23:10 UTC, finnar-bin commented
> Hmm why not just use html image fallback?

That something I actually haven't thought off, lemme check that out

2024-10-29 01:03 UTC, finnar-bin commented
@agalin920 updated to use the image resolver

2024-11-04 23:13 UTC, agalin920 approved these changes

2024-11-05 04:53 UTC, merged