Do not log network errors to sentry
zesty-io/manager-ui pull request #3083
Opened 2024-11-25 06:46 UTC by finnar-bin

Resolves #3074

2024-11-25 19:09 UTC, agalin920 requested changes

2024-11-25 19:09 UTC, agalin920 commented on src/utility/request.js
> -        Sentry.captureException(err, { fingerprint: ["network_error"] });
This line is meant  to fingerprint the error in order to aggregate them. The error is still being thrown below this line.

An unhandled promise rejection is typically treated as an unhandled error by Sentry so this doesn't resolve what the PR aims to resolve.

All this change would do is de-aggregate them and make more noise

2024-11-25 22:37 UTC, finnar-bin commented on src/utility/request.js
> -        Sentry.captureException(err, { fingerprint: ["network_error"] });
@agalin920 I see. I assume removing the throw error below this line would be enough? We're already dispatching a notification in the UI when this happens anyway.

2024-11-25 23:18 UTC, agalin920 commented on src/utility/request.js
> -        Sentry.captureException(err, { fingerprint: ["network_error"] });
Right. I believe so

2024-11-26 01:45 UTC, finnar-bin commented on src/utility/request.js
> -        Sentry.captureException(err, { fingerprint: ["network_error"] });
Updated

2024-11-27 04:46 UTC, agalin920 approved these changes

2024-12-06 04:50 UTC, merged