[Content | Schema] Block Selector
zesty-io/manager-ui pull request #3090
Opened 2024-12-06 04:51 UTC by finnar-bin

Resolves #3052 

### Preview
[screen-recorder-fri-dec-06-2024-12-47-33.webm](https://github.com/user-attachments/assets/68c028ef-2671-477b-93a1-7a710110a9b6)

2025-01-14 00:32 UTC, agalin920 requested changes

2025-01-14 00:32 UTC, agalin920 commented on src/shell/components/FieldTypeBlockSelector/VariantSelector.tsx
> +                    src="https://via.placeholder.com/468x320"
error

2025-01-15 00:52 UTC, finnar-bin commented on src/shell/components/FieldTypeBlockSelector/VariantSelector.tsx
> +                    src="https://via.placeholder.com/468x320"
Updated

2025-01-15 01:20 UTC, agalin920 approved these changes

2025-01-15 05:42 UTC, merged