[3096] Content-Create-Item: Added an identifier when user inputs meta…
zesty-io/manager-ui pull request #3110
Opened 2024-12-27 04:50 UTC by geodem127

… discription manualy

2024-12-30 22:44 UTC, agalin920 requested changes

2024-12-30 22:44 UTC, agalin920 commented on src/apps/content-editor/src/app/components/Editor/Editor.js
> +  const { data, web } = useSelector(
The item is already in scope e.g the item prop. Don't see the reason for this selector

2024-12-30 22:50 UTC, agalin920 requested changes

2024-12-30 22:50 UTC, agalin920 commented on src/apps/content-editor/src/app/components/Editor/Editor.js
> +  useEffect(() => {
This logic is really hard to follow. I would expect this logic to exist within the call stack of the change handler. But will let @finnar-bin weigh in as well

2024-12-30 22:50 UTC, agalin920 commented on src/apps/content-editor/src/app/components/Editor/Editor.js
> +    const isDescriptionChanged = data?.description !== web?.metaDescription;
Careful here, this is incorrect. Data key is the set fields on a model. Therefore data.description is not a guaranteed field nor is the set logic looking for this field. Fields are defined by the user e.g myDescription, someDescription, mySecondTextField etc...

2025-01-02 00:09 UTC, finnar-bin requested changes

2025-01-02 00:09 UTC, finnar-bin commented on src/apps/content-editor/src/app/components/Editor/Editor.js
> +  useEffect(() => {
Yeah I kind of agree with what @agalin920 commented.

Correct me if I'm wrong but wouldn't it be easier to just have 3 states (metaDescription, og_description and tc_description) that holds a boolean value, then set the state to true if the user has done a manual input on those fields (the field names are static so it should be easy to find out through the onChange handler if any of those fields have been manually updated). Then on [these lines](https://github.com/zesty-io/manager-ui/blob/bd3beb6baf5e1b54c8d0d9b32e1378a59e68ceb4/src/apps/content-editor/src/app/components/Editor/Editor.js#L293C1-L316C12) do not do the dispatch if the state is true since that would mean the user has performed a manual update.

2025-01-02 04:17 UTC, geodem127 commented on src/apps/content-editor/src/app/components/Editor/Editor.js
> +  useEffect(() => {
@finnar-bin , this would be the case if "description" and "metaDescription" consistently matched after the page load (without persisting any data). I had a similar thought initially, but things get more complex when the user refreshes the page or navigates to a different one. In such scenarios, metaDescription retains its previous value even if the meta component hasn’t fully loaded in the view, causing it to mistakenly assume that metaDescription has changed. That said, I might have missed something, so a walkthrough would be helpful to clarify.

2025-01-02 04:25 UTC, geodem127 commented on src/apps/content-editor/src/app/components/Editor/Editor.js
> +  const { data, web } = useSelector(
Sorry, I totally missed it. Updated this already

2025-01-30 15:18 UTC, closed without merging