Feature/#762 content filter
zesty-io/manager-ui pull request #775
Opened 2021-06-24 22:40 UTC by d88naimi

2021-06-25 17:30 UTC, d88naimi commented
Ready for a review 
https://8-f48cf3a682-7fthvk.manager.dev.zesty.io/content
https://www.loom.com/share/016918160533461ba0a3b331b67e98bc

2021-06-29 17:59 UTC, shrunyan requested changes
Can the new component we pulled out into a new file? The line count on this component file is getting a bit unwieldy. Making it difficult to comprehend.

2021-06-29 18:46 UTC, d88naimi commented
Extracted itemFilter into a separate component

2021-06-29 20:17 UTC, shrunyan approved these changes

2021-06-29 20:18 UTC, merged