Hot Fix for global account Avatar toggle menu
zesty-io/manager-ui pull request #917
Opened 2021-11-10 22:00 UTC by d88naimi

Issue:
When selecting the global account avatar you can open the menu but then unable to click to close. 
https://www.loom.com/share/313a7a4089564829a071a9ecd06e6710

2021-11-10 22:54 UTC, d88naimi commented
@shrunyan any particular reason why  `evt.stopPropagation();` is commented out? When I uncomment stopPropagation 
https://github.com/zesty-io/manager-ui/blob/master/src/shell/components/global-account/GlobalAccount.js#L44

2021-11-10 22:56 UTC, d88naimi commented
@shrunyan Any particular  reason why stopPropagation is commented out ? When I uncomment stopPropagation that seems to fix the issue I reported in this PR.
https://github.com/zesty-io/manager-ui/blob/master/src/shell/components/global-account/GlobalAccount.js#L44

2021-11-12 20:11 UTC, shrunyan commented
Seems like an erroneous commit from some development that was happening. https://github.com/zesty-io/manager-ui/commit/21a229f4b1ccc7b8e577c953642f5f8973403b3e#diff-21cb17127e58326f6ab4f56620093a560c82120b709a5054dd0fd7598b4dd0a0R42

2021-11-12 20:12 UTC, shrunyan commented on cypress/integration/content/navigation_spec.js
> +    cy.get("[data-cy=globalAccountAvatar]").click();
If it's open and close should there a second assertion of "should not exist"?

2021-11-23 18:59 UTC, shrunyan requested changes

2021-11-23 18:59 UTC, shrunyan commented on src/shell/components/global-account/GlobalAccount.js
> +  const handleClickOutside = (event) => {
This function definition needs to stay inside the `useEffect.` As the reference will change on re-renders causing the `removeEventListener` to use a different reference, resulting in a memory leak.

2021-11-30 18:34 UTC, shrunyan approved these changes

2021-11-30 18:34 UTC, merged