removed formatName on field item edit title
zesty-io/manager-ui pull request #992
Opened 2022-03-09 20:53 UTC by d88naimi

Fixes #99
![Screen Shot 2022-03-09 at 12 52 36 PM](https://user-images.githubusercontent.com/22800749/157533912-9b0bee93-202c-43d1-9e9d-6163cc79ec98.png)
1

2022-03-10 17:06 UTC, shrunyan requested changes

2022-03-10 17:06 UTC, shrunyan commented on src/apps/schema/src/app/views/SchemaEdit/FieldSettings/FieldSettings.js
> +              props.updateValue(val, name);
The name does need to be formatted.

2022-03-10 17:11 UTC, d88naimi commented on src/apps/schema/src/app/views/SchemaEdit/FieldSettings/FieldSettings.js
> +              props.updateValue(val, name);
Sorry I reverted that specific one

2022-03-11 00:17 UTC, shrunyan approved these changes

2022-03-11 21:29 UTC, merged